name: textlint

on:
  push:
    branches: [main]

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: install
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: textlint
        run: yarn lint
